import { ThemeProvider } from "@/components/ThemeProvider";
import "@/assets/css/style.css";
import Header from "@/layouts/Header";

import { Locale, i18n } from "../../../i18n.config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang} suppressHydrationWarning className="transition-colors">
      <head>
        <meta name="description" content={lang.description} />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>

      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
          themes={["light", "dark"]}
        >
          <Header lang={lang} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
